---

- name: Run ldconfig
  command: ldconfig
  when: sssd_compile.changed

- name: Pam auth update
  ignore_errors: yes
  command: pam-auth-update --package
  register: sssd_pam_update
  changed_when: sssd_pam_update.rc != 0
  when: ansible_os_family == "Debian"

- name: Set permissions
  file:
    group: "{{ item.value.group }}"
    mode: "{{ item.value.mode }}"
    owner: "{{ item.value.owner }}"
    path: "{{ item.key }}"
  loop: "{{ sssd_postinst_set_permissions | dict2items }}"
  when: sssd_postinst_set_permissions

- name: Add sss database to /etc/nsswitch.conf
  replace:
    dest: /etc/nsswitch.conf
    regexp: '^(?={{ item }}:(.*))(?:(?!sss).)+$'
    replace: '{{ item }}:\1 sss'
  loop: "{{ sssd_add_sss_to_nss_databases | flatten(levels=1) }}"
